verification_expiry = 5.0 # minutes

[http_api]
port = 8080
custom_protocol = "esefex"

[database]
sounddb_location = "./data/sounds"
userdb_location = "./data/users/users.json"
permissiondb_location = "./data/permissions/permissions.json"
cmd_hash_store_location = "./data/commands/cmd_hash.json"

[bot]
use_timeouts = false
timeout = 60.0 # minutes
