[http_api]
port = 8080
custom_protocol = "esefex"

[file_sound_database]
location = "./data/sounds"

[file_user_database]
location = "./data/users/users.json"

[bot]
use_timeouts = false
timeout = 60.0 # minutes
