[http_api]
port = 8080
domain = "http://159.89.111.82:8080"
# domain = "http://localhost:8080"
custom_protocol = "esefex"

[file_sound_database]
location = "./data/sounds"

[file_user_database]
location = "./data/users/users.json"

[bot]
use_timeouts = false
timeout = 60.0 # minutes
