name: Go Backend CI/CD

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Test Docker Image
        run: docker build -t jokil/esefexapi:test -f EsefexApi/Dockerfile.test EsefexApi

      - name: Run Tests in Docker Container
        run: doocker run jokil/esefexapi:test go test ./...

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Prod Docker Image
        run: docker build -t jokil/esefexapi:latest -f EsefexApi/Dockerfile EsefexApi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push jokil/esefexapi:latest

      - name: Deploy to Production
        run: |
          # SSH into your production server
          ssh esefexapi@159.89.111.82 "cd /api && \
            docker-compose down && \
            docker-compose pull && \
            docker-compose up -d"
